version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  build-orion-migration:
    type: boolean
    default: false
  build-gentrack-migration:
    type: boolean
    default: false
  build-all-migrations:
    type: boolean
    default: false

jobs:

  build_successful:
    parameters:
      scalaModuleName:
        description: this is a test
        type: string
    executor: base
    steps:
      - checkout
      - run:
          command: ./.circleci/bin/common/publish-docker-image-to-ecr.sh  << parameters.scalaModuleName >>
      - run:
          command: echo build 1 completed successfully

  gentrack:
    executor: base
    steps:
      - run:
          command: |
            echo gentrack completed successfully

  orion:
    executor: base
    steps:
      - run:
          command: |
            echo orion completed successfully


  orion_11:
    executor: base
    steps:
      - run:
          command: |
            echo "orion 11"

  orion_12:
    executor: base
    steps:
      - run:
          command: |
            echo "orion 12"

  gentrack_21:
    executor: base
    steps:
      - run:
          command: |
            echo "gentrack 21"

  gentrack_22:
    executor: base
    steps:
      - run:
          command: |
            echo "gentrack 22"

  common-build:
    executor: base
    steps:
      - run:
          command: |
            echo "common-build"

  gt-build:
    executor: base
    steps:
      - run:
          command: |
            echo "gt-build"

  orion-build:
    executor: base
    steps:
      - run:
          command: |
            echo "orion-build"

workflows:
  version: 2
  build-orion-migration:
    when:
      and:
        - << pipeline.parameters.build-orion-migration >>
        - not: << pipeline.parameters.build-gentrack-migration >>
        - not: << pipeline.parameters.build-all-migrations >>
    jobs:
      - orion-build:
          name: orion-build

      - orion_11:
          name: orion_11
          requires:
            - orion-build

      - orion_12:
          name: orion_12
          requires:
            - orion-build

      - build_successful:
          scalaModuleName: orion
          requires:
            - orion_11
            - orion_12

  build-gentrack-migration:
    when:
      and:
        - << pipeline.parameters.build-gentrack-migration >>
        - not: << pipeline.parameters.build-orion-migration >>
        - not: << pipeline.parameters.build-all-migrations >>
    jobs:
      - gt-build:
          name: gt-build

      - gentrack_21:
          name: gentrack_21
          requires:
            - gt-build

      - gentrack_22:
          name: gentrack_22
          requires:
            - gt-build

      - build_successful:
          scalaModuleName: gentrack
          requires:
            - gentrack_21
            - gentrack_22

  build-all-migrations:
    when:
      or:
        - << pipeline.parameters.build-all-migrations >>
        - and:
            - << pipeline.parameters.build-orion-migration >>
            - << pipeline.parameters.build-gentrack-migration >>
    jobs:
      - common-build:
          name: common-build
      - gentrack_21:
          name: gentrack_21
          requires:
            - common-build
      - gentrack_22:
          name: gentrack_22
          requires:
            - common-build
      - gentrack:
          requires:
            - gentrack_21
            - gentrack_22

      - orion_11:
          name: orion_11
          requires:
            - common-build
      - orion_12:
          name: orion_12
          requires:
            - common-build
      - orion:
          requires:
            - orion_11
            - orion_12

      - build_successful:
          scalaModuleName: "gentrack and orion"
          requires:
            - gentrack
            - orion
