version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:stable

parameters:
  project-one:
    type: boolean
    default: false
  project-two:
    type: boolean
    default: false
  project-three:
    type: boolean
    default: false
  run-them-all:
    type: boolean
    default: false

jobs:

  build_successful:
    executor: base
    steps:
      - run:
          command: |
            echo build complete successfully


  project_11:
    executor: base
    steps:
      - run:
          command: |
            echo "project 11"

  project_12:
    executor: base
    steps:
      - run:
          command: |
            echo "project 12"

  project_21:
    executor: base
    steps:
      - run:
          command: |
            echo "project 21"

  project_22:
    executor: base
    steps:
      - run:
          command: |
            adfaf

  project_31:
    executor: base
    steps:
      - run:
          command: |
            echo "project 31"

  project_32:
    executor: base
    steps:
      - run:
          command: |
            echo "project 32"

  all_projects:
    executor: base
    steps:
      - run:
          command: |
            echo "all" 

workflows:
  version: 2
  build-1:
    when:
      or:
        - << pipeline.parameters.project-one >>
        - << pipeline.parameters.run-them-all >>
    jobs:
      - project_11:
          name: project_11
      - project_12:
          name: project_12
      - build_successful:
          requires:
            - project_11
            - project_12


  build-2:
    when:
      or:
        - << pipeline.parameters.project-two >>
        - << pipeline.parameters.run-them-all >>
    jobs:
      - project_21:
          name: project_21
      - project_22:
          name: project_22
      - build_successful:
          requires:
            - project_21
            - project_22

  build-3:
    when:
      or:
        - << pipeline.parameters.project-three >>
        - << pipeline.parameters.run-them-all >>
    jobs:
      - project_31:
          name: project_31
      - project_32:
          name: project_32
      - build_successful:
          requires:
            - project_31
            - project_32

  build-shared-other:
    when: << pipeline.parameters.run-them-all >>
    jobs:
      - all_projects:
          name: all_projects
      - build_successful:
          requires:
            - all_projects


